import { describe,it,expect } from 'vitest';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync,readdirSync } from 'node:fs';
import worker,{parseEvent} from './worker.js';
import { buildFunnelReport,funnelApi,sanitizeJourney } from './funnel.js';
const DAY=86400000, now=Date.now(), token='test-private-key-that-is-at-least-32-characters';
function database(){const raw=new DatabaseSync(':memory:');for(const name of readdirSync(new URL('../drizzle',import.meta.url)).filter(n=>n.endsWith('.sql')).sort())raw.exec(readFileSync(new URL(`../drizzle/${name}`,import.meta.url),'utf8'));const prepare=sql=>{const bind=(args=[])=>({bind:(...a)=>bind(a),all:async()=>({results:raw.prepare(sql).all(...args)}),first:async()=>raw.prepare(sql).get(...args)??null,run:async()=>({meta:{changes:Number(raw.prepare(sql).run(...args).changes)}})});return bind();};return{raw,prepare,batch:async statements=>{raw.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());raw.exec('COMMIT');return results;}catch(e){raw.exec('ROLLBACK');throw e;}}};}
function visit(db,player,at,overrides={}){const id=crypto.randomUUID(),fields={player_id:player,visit_id:id,session_id:crypto.randomUUID(),run_id:crypto.randomUUID(),started_at:at,last_active_at:at+120000,event_at:at+120000,foreground_ms:120000,play_at:at+1000,intro_at:null,work_at:at+1000,spin_at:at+2000,upgrade_at:null,jackpot_at:null,clear_at:null,second_bet_at:null,language:'ja',device:'mobile',version:'3.0.0',mode:'normal',origin:'new',debug:0,modal:'none',tab:'spin',status:'cash',...overrides};db.raw.prepare(`INSERT INTO funnel_segments (${Object.keys(fields)}) VALUES (${Object.keys(fields).map(()=>'?')})`).run(...Object.values(fields));db.raw.prepare('INSERT OR IGNORE INTO funnel_devices VALUES(?,?,?)').run(player,id,at);return fields;}
const report=db=>buildFunnelReport(db,new URLSearchParams('horizon=72'),now);
describe('private funnel reporting',()=>{
 it('censors young cohorts; excludes page-only returns; counts late returns separately',async()=>{const db=database();visit(db,'a',now-5*DAY);visit(db,'a',now-DAY);visit(db,'b',now-5*DAY);visit(db,'b',now-DAY,{play_at:null,foreground_ms:0});visit(db,'c',now-DAY);const r=await report(db);expect(r.summary).toMatchObject({devices:3,players:3,matured:2,returned:0,returnedEver:1,pending:1,shortMatured:2,shortReturnedEver:1});expect(r.insights.join('')).toContain('現時点まで再プレイ');});
 it('includes later language, version and LAB changes as actual return, not as a new acquisition',async()=>{const db=database();visit(db,'a',now-5*DAY);visit(db,'a',now-4*DAY,{language:'en',version:'3.1.0',debug:1});visit(db,'lab',now-5*DAY,{debug:1});const r=await buildFunnelReport(db,new URLSearchParams('horizon=72&language=ja&version=3.0.0'),now);expect(r.summary).toMatchObject({devices:1,returned:1});});
 it('does not count overlapping tabs as a separate return',async()=>{const db=database();visit(db,'a',now-5*DAY);visit(db,'a',now-5*DAY+30000);expect((await report(db)).summary.returned).toBe(0);});
 it('uses page maxima across run resets and sums reload contributions',async()=>{const db=database(),a=visit(db,'a',now-5*DAY,{foreground_ms:400000});visit(db,'a',a.started_at,{visit_id:a.visit_id,session_id:a.session_id,foreground_ms:450000});visit(db,'a',a.started_at,{visit_id:a.visit_id,foreground_ms:160000});expect((await report(db)).summary.shortMatured).toBe(0);});
 it('handles exact horizon maturity and independent optional milestones',async()=>{const db=database();visit(db,'a',now-3*DAY-1000,{play_at:now-3*DAY,work_at:null,upgrade_at:now-3*DAY+10000,jackpot_at:now-3*DAY+20000,clear_at:now-3*DAY+30000});const r=await report(db);expect(r.summary.matured).toBe(1);expect(r.stages.map(s=>s.count)).toEqual([1,1,1,1,1]);expect(r.summary.work).toBe(0);});
 it('does not truncate cohorts at 10,000 records',async()=>{const db=database();db.raw.exec('BEGIN');for(let i=0;i<10005;i++)visit(db,`p${i}`,now-5*DAY);db.raw.exec('COMMIT');expect((await report(db)).summary.devices).toBe(10005);},30000);
 it('fails closed before querying the database and returns no IDs',async()=>{const url=new URL('https://game.test/api/analytics/funnel');const db={prepare:()=>{throw new Error('must not query');}};expect((await funnelApi(new Request(url),{DB:db},url)).status).toBe(503);expect((await funnelApi(new Request(url),{DB:db,ANALYTICS_READ_TOKEN:token},url)).status).toBe(401);const good=database();visit(good,'private-id',now-5*DAY);const r=await funnelApi(new Request(url,{headers:{Authorization:`Bearer ${token}`}}),{DB:good,ANALYTICS_READ_TOKEN:token},url);expect(r.status).toBe(200);expect(r.headers.get('Cache-Control')).toContain('no-store');expect(await r.text()).not.toContain('private-id');});
});
describe('funnel ingestion',()=>{
 const make=(overrides={})=>({eventId:crypto.randomUUID(),runId:crypto.randomUUID(),sessionId:crypto.randomUUID(),sequence:0,activeMs:1000,engagedMs:1000,eventName:'milestone',appVersion:'3.0.0',rulesetVersion:'astra-v13:classic',schemaVersion:3,debug:false,language:'ja',deviceClass:'mobile',viewportClass:'small',props:{name:'visit_spin',gameStatus:'cash',journey:{id:crypto.randomUUID(),start:now-5000,active:now,at:now,play:now-1000,foreground:1000,origin:'new',language:'ja',device:'mobile',version:'3.0.0',mode:'normal'}},...overrides});
 const send=(DB,installId,events,method='POST')=>worker.fetch(new Request('https://game.test/api/telemetry',{method,headers:{origin:'https://game.test','Content-Type':'application/json'},body:JSON.stringify({installId,events})}),{DB});
 it('projects only immutable accepted rows and deletes all visit data on opt-out',async()=>{const DB=database(),install=crypto.randomUUID(),event=make();const first=await send(DB,install,[event]);expect(first.status).toBe(202);expect(await first.json()).toEqual({accepted:1,ignored:0});const altered={...event,props:{...event.props,journey:{...event.props.journey,id:crypto.randomUUID(),foreground:999999}}};expect((await send(DB,install,[altered])).status).toBe(202);expect(DB.raw.prepare('SELECT COUNT(*) n,MAX(foreground_ms) ms FROM funnel_segments').get()).toMatchObject({n:1,ms:1000});expect((await send(DB,install,undefined,'DELETE')).status).toBe(200);expect(DB.raw.prepare('SELECT COUNT(*) n FROM funnel_segments').get().n).toBe(0);expect(DB.raw.prepare('SELECT COUNT(*) n FROM funnel_devices').get().n).toBe(0);});
 it('accepts existing telemetry and reports preparation status before the migration',async()=>{const DB=database();DB.raw.exec('DROP TABLE funnel_segments; DROP TABLE funnel_devices;');const install=crypto.randomUUID();expect((await send(DB,install,[make()])).status).toBe(202);expect((await report(DB)).collectionStatus).toBe('schema_pending');expect((await send(DB,install,undefined,'DELETE')).status).toBe(200);});
 it('keeps legacy events and drops invalid journey metadata without rejecting play stats',()=>{const e=make();expect(parseEvent({...e,schemaVersion:2}).props.journey).toBeUndefined();expect(parseEvent({...e,props:{...e.props,journey:{...e.props.journey,at:now+DAY}}})).not.toBeNull();expect(sanitizeJourney({...e.props.journey,active:now+DAY})).toBeUndefined();});
});
